version: '3' # composeファイルのバーション指定
services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile.multi-stage-build
    tty: true # コンテナの起動永続化
    volumes:
      - .:/go/src/work # マウントディレクトリ指定
    ports:
      - "127.0.0.1:9000:9000" # ここを変更していく

